version: '3.7'

services:
    cron:
        build: .
        image: qsoyq/cron
        container_name: cron
        platform: linux/amd64
        restart: unless-stopped
        volumes:
          - $PWD/crontab:/root/crontabs/cron
          - $PWD/logs:/root/logs
